version: "3"

services:
  postgres:
    image: postgres:15
    container_name: chat-app-db
    environment:
      - POSTGRES_DB=chatapp
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpass
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    container_name: chat-app
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chatapp
      - SPRING_DATASOURCE_USERNAME=chatuser
      - SPRING_DATASOURCE_PASSWORD=chatpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data:
networks:
  app-network:
    driver: bridge
