version: "2.8"

services:
  postgres:
    image: postgres:15
    container_name: chat-app-db
    environment:
      - POSTGRES_DB=chatapp
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Монтируем папку с CSV файлами внутрь контейнера
      - ./src/main/resources/db/data:/docker-entrypoint-initdb.d/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatuser -d chatapp"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  app:
    build: .
    container_name: chat-app
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/chatapp
      - SPRING_DATASOURCE_USERNAME=chatuser
      - SPRING_DATASOURCE_PASSWORD=chatpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
